config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.super.urls', namespace='super')),
    path('security/', include('core.security.urls', namespace='security')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

core/super/urls.py
from django.urls import path 
from core.super.views import customer, product, seller, sale, scan_barcode, shop, cart, chatbot
from core.super.views import home

app_name = 'super'

urlpatterns = [
    # HOME
    path('', home.HomeView.as_view(), name='home'),
    path('about/', home.AboutView.as_view(), name='about'),
    path('contact/', home.ContactView.as_view(), name='contact'),
    path('catalogo/', home.ProductCatalogView.as_view(), name='catalog'),

    # TIENDA PARA CLIENTES
    path('tienda/', shop.ShopView.as_view(), name='shop'),
    path('producto/<int:pk>/', shop.ProductDetailCustomerView.as_view(), name='product_detail_customer'),
    
    # CARRITO
    path('carrito/', cart.CartView.as_view(), name='cart'),
    path('carrito/agregar/<int:product_id>/', cart.add_to_cart, name='add_to_cart'),
    path('carrito/actualizar/<int:item_id>/', cart.update_cart_item, name='update_cart_item'),
    path('carrito/eliminar/<int:item_id>/', cart.remove_from_cart, name='remove_from_cart'),
    path('carrito/checkout/', cart.CheckoutView.as_view(), name='checkout'),
    path('cart/count/', cart.cart_count, name='cart_count'),
    
    # MIS COMPRAS
    path('mis-compras/', shop.MyOrdersView.as_view(), name='my_orders'),
    path('mis-compras/<int:pk>/', shop.OrderDetailView.as_view(), name='order_detail'),

    # ADMIN MENU
    path('menu/', home.MenuView.as_view(), name='menu'),

    # CLIENTES (ADMIN)
    path('clientes/', customer.CustomerListView.as_view(), name='customer_list'),
    path('clientes/crear/', customer.CustomerCreateView.as_view(), name='customer_create'),
    path('clientes/editar/<int:pk>/', customer.CustomerUpdateView.as_view(), name='customer_update'),
    path('clientes/eliminar/<int:pk>/', customer.CustomerDeleteView.as_view(), name='customer_delete'),

    # VENDEDORES (ADMIN)
    path('vendedores/', seller.SellerListView.as_view(), name='seller_list'), 
    path('vendedores/crear/', seller.SellerCreateView.as_view(), name='seller_create'),
    path('vendedores/editar/<int:pk>/', seller.SellerUpdateView.as_view(), name='seller_update'),
    path('vendedores/eliminar/<int:pk>/', seller.SellerDeleteView.as_view(), name='seller_delete'),

    # PRODUCTOS (ADMIN)
    path('productos/', product.ProductListView.as_view(), name='product_list'),
    path('productos/crear/', product.ProductCreateView.as_view(), name='product_create'),
    path('productos/editar/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
    path('productos/eliminar/<int:pk>/', product.ProductDeleteView.as_view(), name='product_delete'),
    path('productos/<int:pk>/', product.ProductDetailView.as_view(), name='product_detail'),

    # VENTAS (ADMIN)
    path('ventas/', sale.SaleListView.as_view(), name='sale_list'),
    path('ventas/crear/', sale.SaleCreateView.as_view(), name='sale_create'),
    path('ventas/editar/<int:pk>/', sale.SaleUpdateView.as_view(), name='sale_update'),
    path('ventas/eliminar/<int:pk>/', sale.SaleDeleteView.as_view(), name='sale_delete'),
    path('ventas/<int:pk>', sale.SaleDetailView.as_view(), name='sale_detail'),
    path('api/products/', sale.ProductView.as_view(), name='get_products'),
    path('ventas/factura/<int:pk>/', sale.SalePDFView.as_view(), name='sale_pdf'),
    
    # ESCANEAR PRODUCTOS
    path('scan_barcode/', scan_barcode.ScannerTemplate.as_view(), name='scan_barcode'),

    # CHATBOT
    path('chatbot/api/', chatbot.ChatbotProxyView.as_view(), name='chatbot_api'),
]

core/super/models.py
from django.db import models
from django.db.models import CheckConstraint, Q
from django.utils import timezone
from django.conf import settings
from decimal import Decimal
from config.utils import get_image
from django.forms import model_to_dict

class Brand(models.Model):
    id_brand = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)

    @property
    def id(self):
        return self.id_brand
    
    def __str__(self):
        return f'Marca : {self.name}'
    
    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        ordering = ['id_brand', 'name'] 
        indexes = [
            models.Index(fields=['name']),
        ]

class Category(models.Model):
    id_category = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)

    @property
    def id(self):
        return self.id_category
    
    def __str__(self):
        return f'Categoria : {self.name}'
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ['id_category', 'name'] 
        indexes = [
            models.Index(fields=['name']),
        ]

class PaymentMethod(models.Model):
    id_payment_method = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)

    @property
    def id(self):
        return self.id_payment_method
    
    def __str__(self):
        return f'Forma de Pago : {self.name}'
    
    class Meta:
        verbose_name = "Forma de Pago"
        verbose_name_plural = "Forma de Pagos"
        ordering = ['id_payment_method', 'name'] 
        indexes = [
            models.Index(fields=['name']),
        ]

class Customer(models.Model):
    class GenderChoices(models.IntegerChoices):
        Male = 1, 'Masculino'
        Female = 2, 'Femenino'
    
    id_customer = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)
    last_name = models.CharField(max_length=100, verbose_name="Apellido", blank=True, null=True)
    dni = models.CharField(max_length=100, verbose_name="Cédula", blank=False, null=False, unique=True)
    email = models.EmailField(max_length=100, verbose_name="Email", blank=True, null=True, unique=True)
    address = models.CharField(max_length=100, verbose_name="Dirección", blank=True, null=True)
    phone = models.CharField(max_length=100, verbose_name="Telefono", blank=True, null=True, unique=True)
    birth_date = models.DateField(verbose_name="Fecha de nacimiento", blank=True, null=True)
    gender = models.IntegerField(choices=GenderChoices.choices, default=GenderChoices.Male, verbose_name="Genero", blank=True, null=True)

    discount_percentage = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        default=Decimal('0.00'), 
        verbose_name="Descuento (%)"
    )

    @property
    def id(self):
        return self.id_customer
    
    def get_full_name(self):
        return f'{self.name} {self.last_name}'
    
    def __str__(self):
        return f'Cliente : {self.get_full_name()}'
    
    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['id_customer', 'name', 'last_name'] 
        indexes = [models.Index(fields=['name']),
                   models.Index(fields=['last_name']),
                   models.Index(fields=['dni']),
                   models.Index(fields=['email']),
                   models.Index(fields=['address']),
                   models.Index(fields=['phone']),
                   models.Index(fields=['birth_date']),
                   models.Index(fields=['gender']),
        ]

class Seller(models.Model):
    class GenderChoices(models.IntegerChoices):
        Male = 1, 'Masculino'
        Female = 2, 'Femenino'

    id_seller = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)
    last_name = models.CharField(max_length=100, verbose_name="Apellido", blank=True, null=True)
    dni = models.CharField(max_length=100, verbose_name="Cédula", blank=False, null=False, unique=True)
    email = models.EmailField(max_length=100, verbose_name="Email", blank=True, null=True, unique=True)
    address = models.CharField(max_length=100, verbose_name="Dirección", blank=True, null=True)
    phone = models.CharField(max_length=100, verbose_name="Telefono", blank=True, null=True, unique=True)
    birth_date = models.DateField(verbose_name="Fecha de nacimiento", blank=True, null=True)
    gender = models.IntegerField(choices=GenderChoices.choices, default=GenderChoices.Male, verbose_name="Genero", blank=True, null=True)

    @property
    def id(self):
        return self.id_seller
    
    def get_full_name(self):
        return f'{self.name} {self.last_name}'
    
    def __str__(self):
        return f'Vendedor : {self.get_full_name()}'
    
    class Meta:
        verbose_name = "Vendedor"
        verbose_name_plural = "Vendedores"
        ordering = ['id_seller', 'name', 'last_name']
        indexes = [models.Index(fields=['name']),
                   models.Index(fields=['last_name']),
                   models.Index(fields=['dni']),
                   models.Index(fields=['email']),
                   models.Index(fields=['address']),
                   models.Index(fields=['phone']),
                   models.Index(fields=['birth_date']),
                   models.Index(fields=['gender']),
        ]

class Product(models.Model):
    id_product = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name="Marca", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Categoria", blank=True, null=True)
    name = models.CharField(max_length=100, verbose_name="Nombre", blank=True, null=True)
    description = models.TextField(verbose_name="Descripción", blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), verbose_name="Precio", blank=True, null=True)
    stock = models.IntegerField(default=0, verbose_name="Stock", blank=True, null=True)
    image = models.ImageField(upload_to='products', verbose_name="Imágen", blank=True, null=True)
    barcode = models.CharField(max_length=100, verbose_name="Código de barras", blank=True, null=True, unique=True)
    production_date = models.DateField(default=timezone.now, verbose_name="Fecha de elaboración", blank=True, null=True)
    expiration_date = models.DateField(verbose_name="Fecha de vencimiento", blank=True, null=True) 
    state = models.BooleanField(default=True, verbose_name="Estado", blank=True, null=True)

    @property
    def id(self):
        return self.id_product

    def save(self, *args, **kwargs):
        self.state = self.stock > 0  # Asegura que el estado se calcule antes de guardar
        super().save(*args, **kwargs)

    def get_image_url(self):
        return get_image(self.image)
    
    def __str__(self):
        return f'Producto : {self.name}'
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['id_product', 'name'] 
        indexes = [models.Index(fields=['name']),
                   models.Index(fields=['brand']),
                   models.Index(fields=['category']),
                   models.Index(fields=['description']),
                   models.Index(fields=['stock']),
                   models.Index(fields=['barcode']),
                   models.Index(fields=['production_date']),
                   models.Index(fields=['expiration_date']),
                   models.Index(fields=['state']),
        ]
        constraints = [
            CheckConstraint(check=Q(stock__gte=0), name='product_stock_non_negative'),
            CheckConstraint(check=Q(price__gt=0), name='product_price_non_negative')
        ]

class Sale(models.Model):
    id_sale = models.AutoField(primary_key=True, verbose_name="ID", blank=False, null=False, unique=True)
    # NUEVO CAMPO: Para saber qué cuenta de usuario hizo la compra
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Usuario que compró", null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="Cliente", blank=True, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, verbose_name="Vendedor", blank=True, null=True)
    payment = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE, verbose_name="Forma de pago", blank=True, null=True)
    sale_date = models.DateTimeField(
        default=timezone.now, 
        verbose_name="Fecha y Hora de venta", 
        blank=True, 
        null=True
    )
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), verbose_name="Subtotal", blank=True, null=True)
    iva = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), verbose_name="IVA", blank=True, null=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), verbose_name="Descuento", blank=True, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), verbose_name="Total", blank=True, null=True)

core/super/views.py
from django.shortcuts import render

# Create your views here.

core/super/views/chatbot.py
import json
from google import genai
from django.conf import settings
from django.http import JsonResponse
from django.views import View

class ChatbotProxyView(View):    
    def post(self, request):
        try:
            data = json.loads(request.body)
            user_message = data.get("message", "")

            if not user_message:
                return JsonResponse({"error": "Mensaje vacío"}, status=400)
            
            # Inicializar cliente (usando la clave que ya verificaste que funciona)
            client = genai.Client(api_key=settings.GEMINI_API_KEY)
            
            # Obtener nombre del usuario para el saludo personalizado
            user_name = request.user.first_name if request.user.is_authenticated else "Invitado"
            
            # Generar contenido usando el modelo que te dio ÉXITO
            response = client.models.generate_content(
                model="gemini-3-flash-preview", # Modelo de Gemini Actualizado
                contents=user_message,
                config={
                    'system_instruction': (
                        f"Eres el asistente virtual de 'My Supermarket'. Saludas a {user_name}. "
                        "Ayudas con dudas sobre productos y facturación. "
                        "Regla de Oro: Si el cliente es 'Consumidor Final', SOLO aceptamos Efectivo. "
                        "Si usa datos personales, acepta Tarjeta o QR. "
                        "Sé amable, usa emojis 🛒 y responde en español de Ecuador."
                    ),
                    'temperature': 0.7,
                }
            )
            
            return JsonResponse({"reply": response.text})
            
        except Exception as e:
            # Imprime el error en la terminal de VS Code para verlo
            print(f"Error en Chatbot: {str(e)}")
            return JsonResponse({"error": str(e)}, status=500)

templates/super/products/product_delete.html
{% extends 'components/base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container mx-auto py-8 px-16">
    <div class="bg-white shadow-lg rounded-lg p-8">
        <h1 class="text-3xl font-bold mb-4">{{description}}</h1>
        <div class="mt-6 flex justify-between">
            <a href="{{back_url}}" class="bg-gray-300 text-black px-6 py-2 rounded-lg hover:bg-gray-400">Cancelar</a>
            <form action="{% url 'super:product_delete' product.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="bg-red-500 text-white px-6 py-2 rounded-lg hover:bg-red-600">{{ grabar }}</button>
            </form> 
        </div> 
    </div> 
</div> 
{% endblock %}

templates/super/products/product_form.html
{% extends 'components/base.html' %}
{% load static %}
{% block title %}{% if producto.pk %}{{ title }}{% else %}{{ title }}{% endif %}{% endblock %}
{% block content %}
<div class="container mx-auto py-8 px-16">
    <h1 class="text-3xl font-bold mb-6">{% if product.pk %}{{ grabar }}{% else %}{{ grabar }}{% endif %}</h1>
    <form method="post" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}

        <div class="mb-6">
            <label for="id_name" class="block text-gray-700 font-semibold mb-2">Nombre del Producto</label> 
            <input type="text" name="name" id="id_name" value="{{ form.instance.name|default:'' }}" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500" 
            placeholder="Ingrese el nombre del producto">
            {% if form.name.errors %} 
               <div class="text-red-500 text-sm mt-2">
                    {% for error in form.name.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
               </div> 
            {% endif %}
        </div> 

        <div class="mb-6">
            <label for="id_category" class="block text-lg font-medium">Categoría</label> 
            <select name="category" id="id_category" class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500">
                <option value="">Seleccionar Categoría</option>
                {% for category in form.category.field.queryset %}
                    <option value="{{ category.pk }}" {% if form.instance.category == category %}selected{% endif %}>{{ category.name }}</option>
                {% endfor %}
            </select>
            {% if form.category.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.category.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div> 

        <div class="mb-6">
            <label for="id_brand" class="block text-lg font-medium">Marca</label> 
            <select name="brand" id="id_brand" class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500">
                <option value="">Seleccionar Marca</option>
                {% for brand in form.brand.field.queryset %}
                    <option value="{{ brand.pk }}" {% if form.instance.brand == brand %}selected{% endif %}>{{ brand.name }}</option>
                {% endfor %}
            </select>
            {% if form.brand.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.brand.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-6">
            <label for="id_description" class="block text-lg font-medium">Descripción</label>
            <textarea name="description" id="id_description" rows="5" class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500">{{ form.instance.descripcion|default:'' }}</textarea>
            {% if form.description.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.description.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-6">
            <label for="id_price" class="block text-lg font-medium">Precio</label>
            <input type="number" name="price" id="id_price" value="{{ form.instance.price|default:'' }}" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500" 
            placeholder="Ingrese el precio del producto" step="0.01" required>
            {% if form.price.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.price.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-6"> 
            <label for="id_stock" class="block text-lg font-medium">Stock</label>
            <input type="number" name="stock" id="id_stock" value="{{ form.instance.stock|default:'' }}" min="0" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500" placeholder="Ingrese el stock del producto" step="1" required>
            {% if form.stock.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.stock.errors %} 
                        <p>{{ error }}</p>
                    {% endfor %}
                </div> 
            {% endif %} 
        </div>

        <div class="mb-6">
            <label for="id_image" class="block text-lg font-medium">Imagen del Producto</label>
            {% if form.instance.image %}
                <div class="mb-4">
                    <img src="{{ form.instance.image.url }}" alt="Imagen del Producto" class="w-32 h-32 object-cover rounded-lg">
                </div>
            {% endif %}
            <input type="file" name="image" id="id_image" class="mt-1 block w-full px-4 py-2 border rounded-lg">
            {% if form.image.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.image.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-6">
            <label for="id_production_date" class="block text-lg font-medium">Fecha de Elaboración</label>
            <input type="date" name="production_date" id="id_production_date" value="{{ form.instance.production_date|default:'' }}" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500" placeholder="Ingrese la fecha de elaboración del producto" required>
            {% if form.production_date.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.production_date.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-6">
            <label for="id_expiration_date" class="block text-lg font-medium">Fecha de Vencimiento</label>
            <input type="date" name="expiration_date" id="id_expiration_date" value="{{ form.instance.expiration_date|default:'' }}" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500" placeholder="Ingrese la fecha de vencimiento del producto" readonly>
            {% if form.expiration_date.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.expiration_date.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %} 
        </div>

        <div class="mb-6">
            <label for="id_state" class="block text-lg font-medium">Estado del Producto</label>
            <input type="text" name="state" id="id_state" value="{{ form.instance.state|yesno:'Agotado,Disponible' }}" readonly>
        </div> 

        <div class="mb-6">
            <label for="id_barcode" class="block text-lg font-medium">Código de Barras</label>
            <input type="text" name="barcode" id="id_barcode" value="{{ form.instance.barcode|default:'' }}" 
            class="mt-1 block w-full px-4 py-2 border rounded-lg focus:ring-green-500 focus:border-green-500 only-numbers" 
            placeholder="Ingrese el código de barras del producto (13 dígitos)" 
            maxlength="13" pattern="[0-9]{13}" autocomplete="off">
            {% if form.barcode.errors %}
                <div class="text-red-500 text-sm mt-2">
                    {% for error in form.barcode.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-all">Guardar Producto</button>
            <a href={{back_url}} class="bg-gray-500 text-white px-6 py-2 rounded-lg hover:bg-gray-600 transition-all">Cancelar</a>
        </div>
    </form> 
</div>
<script src="{% static 'js/expiration_date.js' %}"></script>
<script src="{% static 'js/state_stock.js' %}"></script>
<script src="{% static 'js/barcode_validation.js' %}"></script>
{% endblock %}

templates/super/products/product_list.html
{% extends 'components/base.html' %}
{% block title %}{{ title }}{% endblock %} 
{% block content %}
<div class="container mx-auto py-8 px-16">
    <h1 class="text-3xl font-bold mb-6">Lista de {{ title }}</h1>
    <div class="mb-6">
        <a href="{{create_url}}" class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition-all">Agregar Nuevo Producto</a>
    </div>
    {% if products %}
        <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-6">
           {% for product in page_obj %} 
                <div class="bg-white shadow-lg rounded-lg overflow-hidden">
                    <img src="{{ product.get_image_url }}" alt="{{ product.name }}" class="w-full h-48 object-cover">
                    <div class="p-4">
                        <h2 class="text-xl font-semibold">{{ product.name }}</h2>
                        <p class="text-gray-500">{{ product.description|truncatewords:20 }}</p>
                        <p class="text-green-600 font-bold">{{ product.price|floatformat:2 }}$</p>
                        <p class="text-gray-600">Stock: {{ product.stock }}</p> 
                        <p class="text-blue-600">
                            {% if product.state %}
                                <span class="text-white-600 font-bold border border-blue-600 text-green-600 rounded-lg px-2 py-1">Disponible</span>
                            {% else %}
                                <span class="text-white-600 font-bold border border-blue-600 text-red-600 rounded-lg px-2 py-1">Agotado</span>
                            {% endif %}
                        </p>
                        <div class="flex justify-between mt-4">
                            <a href="{% url 'super:product_detail' product.pk %}" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-cyan-600">Ver Detalles</a> 
                            <a href="{% url 'super:product_update' product.pk %}" class="bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600">Editar</a> 
                            <a href="{% url 'super:product_delete' product.pk %}" class="bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600">Eliminar</a>
                        </div> 
                    </div> 
                </div> 
           {% endfor %}
        </div>
    {% else %}
        <p class="text-lg text-gray-500">No hay productos disponibles en esta categoría o búsqueda.</p>
    {% endif %}

    <!-- Pagination -->
    <div class="mt-6">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="px-4 py-2 bg-gray-300 text-black rounded-lg hover:bg-gray-400">Primera</a> 
            <a href="?page={{ page_obj.previous_page_number }}" class="px-4 py-2 bg-gray-300 text-black rounded-lg hover:bg-gray-400">Anterior</a>
        {% endif %}
        <span class="mx-2 text-lg">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="px-4 py-2 bg-gray-300 text-black rounded-lg hover:bg-gray-400">Siguiente</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="px-4 py-2 bg-gray-300 text-black rounded-lg hover:bg-gray-400">Última</a>
        {% endif %}
    </div> 
</div> 
{% endblock %}